/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WheelockRouteImport } from './routes/wheelock'
import { Route as WhatsNextRouteImport } from './routes/whats-next'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as CourseworkRouteImport } from './routes/coursework'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as BeforeRouteImport } from './routes/before'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WheelockRoute = WheelockRouteImport.update({
  id: '/wheelock',
  path: '/wheelock',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsNextRoute = WhatsNextRouteImport.update({
  id: '/whats-next',
  path: '/whats-next',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseworkRoute = CourseworkRouteImport.update({
  id: '/coursework',
  path: '/coursework',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const BeforeRoute = BeforeRouteImport.update({
  id: '/before',
  path: '/before',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/before': typeof BeforeRoute
  '/clubs': typeof ClubsRoute
  '/coursework': typeof CourseworkRoute
  '/research': typeof ResearchRoute
  '/whats-next': typeof WhatsNextRoute
  '/wheelock': typeof WheelockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/before': typeof BeforeRoute
  '/clubs': typeof ClubsRoute
  '/coursework': typeof CourseworkRoute
  '/research': typeof ResearchRoute
  '/whats-next': typeof WhatsNextRoute
  '/wheelock': typeof WheelockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/before': typeof BeforeRoute
  '/clubs': typeof ClubsRoute
  '/coursework': typeof CourseworkRoute
  '/research': typeof ResearchRoute
  '/whats-next': typeof WhatsNextRoute
  '/wheelock': typeof WheelockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/before'
    | '/clubs'
    | '/coursework'
    | '/research'
    | '/whats-next'
    | '/wheelock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/before'
    | '/clubs'
    | '/coursework'
    | '/research'
    | '/whats-next'
    | '/wheelock'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/before'
    | '/clubs'
    | '/coursework'
    | '/research'
    | '/whats-next'
    | '/wheelock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BeforeRoute: typeof BeforeRoute
  ClubsRoute: typeof ClubsRoute
  CourseworkRoute: typeof CourseworkRoute
  ResearchRoute: typeof ResearchRoute
  WhatsNextRoute: typeof WhatsNextRoute
  WheelockRoute: typeof WheelockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wheelock': {
      id: '/wheelock'
      path: '/wheelock'
      fullPath: '/wheelock'
      preLoaderRoute: typeof WheelockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whats-next': {
      id: '/whats-next'
      path: '/whats-next'
      fullPath: '/whats-next'
      preLoaderRoute: typeof WhatsNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coursework': {
      id: '/coursework'
      path: '/coursework'
      fullPath: '/coursework'
      preLoaderRoute: typeof CourseworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/before': {
      id: '/before'
      path: '/before'
      fullPath: '/before'
      preLoaderRoute: typeof BeforeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BeforeRoute: BeforeRoute,
  ClubsRoute: ClubsRoute,
  CourseworkRoute: CourseworkRoute,
  ResearchRoute: ResearchRoute,
  WhatsNextRoute: WhatsNextRoute,
  WheelockRoute: WheelockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
